// gen-events parses sdk/streaming.go, sdk/interrupt.go, and sdk/artifact.go,
// extracts the typed string constants the wire protocol uses, and emits
// clients/harness-client/src/generated/events.ts as a set of strict
// TypeScript union types.
//
// Why a separate generator? tygo emits each constant individually and types
// the alias as a plain `string`. That lets clients pass any string to a
// session.on() listener which defeats the purpose of generating from Go.
// This generator produces:
//
//   export type StreamEventName = "delta" | "tool_call" | ...
//   export type InterruptKindName = "approval" | ...
//   export const StreamEventNames: readonly StreamEventName[] = [...] as const;
//
// Run via `make client-events` (or directly: go run ./scripts/gen-events).
// The CI guard `make client-types-check` regenerates and fails on diff.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type extractedConst struct {
	Name  string
	Value string
}

type group struct {
	tsName    string // e.g. "StreamEventName"
	tsListVar string // e.g. "StreamEventNames"
	goPrefix  string // e.g. "StreamEvent"
	goType    string // e.g. "StreamEventType"
	items     []extractedConst
}

var groups = []*group{
	{tsName: "StreamEventName", tsListVar: "StreamEventNames", goPrefix: "StreamEvent", goType: "StreamEventType"},
	{tsName: "InterruptKindName", tsListVar: "InterruptKindNames", goPrefix: "InterruptKind", goType: "InterruptKind"},
	{tsName: "ArtifactKindName", tsListVar: "ArtifactKindNames", goPrefix: "ArtifactKind", goType: "ArtifactKind"},
}

func main() {
	repoRoot, err := os.Getwd()
	if err != nil {
		die(err)
	}
	sdkDir := filepath.Join(repoRoot, "sdk")

	if err := scan(sdkDir); err != nil {
		die(err)
	}

	out := render()
	dest := filepath.Join(repoRoot, "clients", "harness-client", "src", "generated", "events.ts")
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		die(err)
	}
	if err := os.WriteFile(dest, []byte(out), 0o644); err != nil {
		die(err)
	}
	fmt.Printf("wrote %s\n", dest)
}

func scan(dir string) error {
	files, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return err
	}
	fset := token.NewFileSet()
	for _, f := range files {
		if strings.HasSuffix(f, "_test.go") {
			continue
		}
		af, err := parser.ParseFile(fset, f, nil, parser.SkipObjectResolution)
		if err != nil {
			return fmt.Errorf("parse %s: %w", f, err)
		}
		for _, decl := range af.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok || vs.Type == nil || len(vs.Names) == 0 || len(vs.Values) == 0 {
					continue
				}
				typeName := exprName(vs.Type)
				for _, g := range groups {
					if typeName != g.goType {
						continue
					}
					name := vs.Names[0].Name
					if !strings.HasPrefix(name, g.goPrefix) {
						continue
					}
					lit, ok := vs.Values[0].(*ast.BasicLit)
					if !ok || lit.Kind != token.STRING {
						continue
					}
					value := strings.Trim(lit.Value, "`\"")
					g.items = append(g.items, extractedConst{Name: name, Value: value})
				}
			}
		}
	}
	for _, g := range groups {
		sort.SliceStable(g.items, func(i, j int) bool { return g.items[i].Value < g.items[j].Value })
	}
	return nil
}

func exprName(e ast.Expr) string {
	if id, ok := e.(*ast.Ident); ok {
		return id.Name
	}
	if sel, ok := e.(*ast.SelectorExpr); ok {
		return sel.Sel.Name
	}
	return ""
}

func render() string {
	var buf bytes.Buffer
	buf.WriteString(`// Code generated by scripts/gen-events. DO NOT EDIT.
// Source: sdk/streaming.go, sdk/interrupt.go, sdk/artifact.go
// Regenerate with: make client-events

`)
	for _, g := range groups {
		if len(g.items) == 0 {
			continue
		}
		buf.WriteString(fmt.Sprintf("// %s — string union of every %s constant in the SDK.\n", g.tsName, g.goType))
		buf.WriteString(fmt.Sprintf("export type %s =\n", g.tsName))
		for i, it := range g.items {
			sep := " |"
			if i == len(g.items)-1 {
				sep = ";"
			}
			buf.WriteString(fmt.Sprintf("  | %q%s\n", it.Value, strings.TrimSuffix(sep, " |")))
		}
		buf.WriteString("\n")
		buf.WriteString(fmt.Sprintf("export const %s = [\n", g.tsListVar))
		for _, it := range g.items {
			buf.WriteString(fmt.Sprintf("  %q,\n", it.Value))
		}
		buf.WriteString(fmt.Sprintf("] as const satisfies readonly %s[];\n\n", g.tsName))
	}
	return buf.String()
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "gen-events:", err)
	os.Exit(1)
}
